version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: Roman
      POSTGRES_PASSWORD: 3mTYklZAs9Gk8946
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"